View(airmiles
     )
View(AirPassengers)
library(forecast)
61306625+AbdalrhmanS99@users.noreply.github.com
r <-  tslm(airmiles ~ trend)
plot(forecast(r,h=50))
r <-  estVar(airmiles ~ trend)
vb <- estVar(BJsales ~ trend+season)
uk <- arima(airmiles,order = c(0,1,1),seasonal = list(order=c(0,1,1)))
plot(uk)
+

plot(forecast(r,h=50))
plot.new(forecast(r,h=50))
plot(r)
r <-  tslm(airmiles ~ trend)
plot(r)
g <- decompose(r,type = "multiplicative")
r <-  tslm(airmiles ~ trend+season)
xn <- auto.arima(airmiles,ic="aic",trace = TRUE)
v <- arima(airmiles)
plot.ts(v$residuals)
v
acf(ts(v,main="acf resff"))
Acf(v)
Acf(ts(v))
pacf(ts(v$residuals),main="pacff")
str(airquality)
airquality <- airquality[complete.cases(airquality),]
str(airquality)
plot.ts(v$residuals)
pacf(ts(v$residuals),main="pacff")
acf(ts(v,main="acf resff"))
acf(ts(v,main="acf"))
acf(ts(v))
ts <- ts(AirPassengers,frequency = 12)
dddd <- decompose(ts,"multiplicative")
plot(dddd)
abline(reg = lm(AirPassengers~time(AirPassengers)))
plot(AirPassengers)
abline(reg = lm(AirPassengers~time(AirPassengers)))
boxplot(AirPassengers~cycle(AirPassengers))
xn <- auto.arima(AirPassengers,ic="aic",trace = TRUE)
library(forecast)
xn <- auto.arima(AirPassengers,ic="aic",trace = TRUE)
uk <- arima(AirPassengers,order = c(0,1,1),seasonal = list(order=c(2,1,0)))
plot(uk)
yyy<- forecast(uk,level = c(95),h=10*14)
plot(yyy)
yyy<- forecast(uk,level = c(95),h=100)
plot(yyy)
yyy<- forecast(uk,level = c(95),h=1000)
plot(yyy)
yyy<- forecast(uk,level = c(95),h=400)
plot(yyy)
yyy<- forecast(uk,level = c(100),h=400)
yyy<- forecast(uk,level = c(99),h=400)
plot(yyy)
abline(reg = lm(AirPassengers~time(AirPassengers)))
h <- ts(AirPassengers,frequency=12)
plot(h)
plot(forecast(h, h=100))
abline(reg = lm(AirPassengers~time(AirPassengers)))
abline(reg = lm(h~time(h)))
